<?php

namespace Alimianesa\SmartAuth;

use Alimianesa\SmartAuth\Resources\LaravelSmartCoding\SmartCoding;
use App\User;
use Illuminate\Database\Eloquent\Model;

class AliveFile extends Model
{
    protected $fillable = [
        'author_id' ,
        'mime_type',
        'title',
        'subtitle',
        'description',
        'uri',
        'size',
        'revoked',
        'thumbnail',
        'thumbnail_id',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->uuid = SmartCoding::encodeToBase32(SmartCoding::timeStampCode());
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'author_id' , 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function speechTexts()
    {
        return $this->belongsToMany(
            SpeechText::class,
            'file_text',
            'file_id',
            'speech_text_id'
            );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany(
            Tag::class,
            'file_tag',
            'file_id',
            'tag_id'
        );
    }
}
