<?php

namespace Alimianesa\SmartAuth;

use Alimianesa\SmartAuth\Resources\LaravelSmartCoding\SmartCoding;
use Illuminate\Database\Eloquent\Model;

class SpeechText extends Model
{
    protected $fillable = [
        'speech_text',
        'active',
        'weight',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->uuid = SmartCoding::encodeToBase32(SmartCoding::timeStampCode());
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function files()
    {
        return $this->belongsToMany(
            AliveFile::class,
            'file_text',
            'speech_text_id',
            'file_id'
    );
    }
}
